dependencies:
  - name: dependencies
    files:
      - package.json
      - package-lock.json
      - renovate.json
      - '**/package.json'
      - '**/yarn.lock'
      - '**/pnpm-lock.yaml'
major:
  - name: major
    files:
      - renovate.json
      - '**/package.json'
backend:
  - name: backend
    files:
      - src/**
      - prisma/**
      - server.js
test:
  - name: test
    files:
      - test/**
