name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
categories:
  - title: "ðŸš€ Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "ðŸ› Bug Fixes"
    labels:
      - "bug"
      - "type/patch"
  - title: "ðŸ§° Maintenance"
    labels:
      - "chore"
      - "type/minor"
      - "type/major"
      - "test"
  - title: "ðŸ“š Documentation"
    labels:
      - "docs"
  - title: "â“ Questions"
    labels:
      - "question"
  - title: "ðŸ‘¥ Community"
    labels:
      - "community"
  - title: "ðŸ”§ GitHub & CI"
    labels:
      - "area/github"
      - "renovate/github-action"
      - "renovate/github-release"
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
