-- Migration: drop_soft_delete_columns
-- Purpose: Remove legacy deletedAt columns by table recreation (SQLite limitation)
-- Generated by automated refactor to hard-delete semantics
PRAGMA foreign_keys = OFF;

-- User table unchanged
-- Recreate Institution without deletedAt
CREATE TABLE "new_Institution" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "userId" TEXT NOT NULL,
  "plaidInstitutionId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "logo" TEXT,
  "primaryColor" TEXT,
  "url" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "Institution_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO
  "new_Institution" (
    "id",
    "userId",
    "plaidInstitutionId",
    "name",
    "logo",
    "primaryColor",
    "url",
    "createdAt",
    "updatedAt"
  )
SELECT
  "id",
  "userId",
  "plaidInstitutionId",
  "name",
  "logo",
  "primaryColor",
  "url",
  "createdAt",
  "updatedAt"
FROM
  "Institution";

DROP TABLE "Institution";

ALTER TABLE "new_Institution"
RENAME TO "Institution";

CREATE UNIQUE INDEX "Institution_userId_plaidInstitutionId_key" ON "Institution" ("userId", "plaidInstitutionId");

-- Recreate Account without deletedAt
CREATE TABLE "new_Account" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "userId" TEXT NOT NULL,
  "plaidItemId" TEXT NOT NULL,
  "institutionId" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "Account_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "Institution" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO
  "new_Account" (
    "id",
    "userId",
    "plaidItemId",
    "institutionId",
    "createdAt",
    "updatedAt"
  )
SELECT
  "id",
  "userId",
  "plaidItemId",
  "institutionId",
  "createdAt",
  "updatedAt"
FROM
  "Account";

DROP TABLE "Account";

ALTER TABLE "new_Account"
RENAME TO "Account";

CREATE UNIQUE INDEX "Account_plaidItemId_key" ON "Account" ("plaidItemId");

-- Recreate PlaidItem without deletedAt
CREATE TABLE "new_PlaidItem" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "userId" TEXT NOT NULL,
  "plaidItemId" TEXT NOT NULL,
  "plaidAccessToken" TEXT NOT NULL,
  "products" TEXT NOT NULL,
  "institutionId" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "PlaidItem_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "PlaidItem_institutionId_fkey" FOREIGN KEY ("institutionId") REFERENCES "Institution" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO
  "new_PlaidItem" (
    "id",
    "userId",
    "plaidItemId",
    "plaidAccessToken",
    "products",
    "institutionId",
    "createdAt",
    "updatedAt"
  )
SELECT
  "id",
  "userId",
  "plaidItemId",
  "plaidAccessToken",
  "products",
  "institutionId",
  "createdAt",
  "updatedAt"
FROM
  "PlaidItem";

DROP TABLE "PlaidItem";

ALTER TABLE "new_PlaidItem"
RENAME TO "PlaidItem";

CREATE UNIQUE INDEX "PlaidItem_plaidItemId_key" ON "PlaidItem" ("plaidItemId");

PRAGMA foreign_keys = ON;
