name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Cache Prisma Client
        id: cache-prisma-lint
        uses: actions/cache@v4
        with:
          path: node_modules/.prisma
          key: prisma-${{ runner.os }}-${{ hashFiles('prisma/schema.prisma') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'
      - name: Cache Prisma Client
        id: cache-prisma-test
        uses: actions/cache@v4
        with:
          path: node_modules/.prisma
          key: prisma-${{ runner.os }}-${{ hashFiles('prisma/schema.prisma') }}
      - name: Install dependencies
        run: npm ci
      - name: Copy .env.example to .env
        run: cp .env.example .env
      - name: Run tests with coverage
        run: npm test -- --coverage --coverageReporters=text-summary --runInBand
        env:
          PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
          PLAID_SECRET: ${{ secrets.PLAID_SECRET }}
          PLAID_ENCRYPTION_KEY: ${{ secrets.PLAID_ENCRYPTION_KEY }}
      - name: Enforce coverage threshold
        run: |
          echo "Checking coverage threshold"
          grep -E 'All files.*\b([0-9]{2,3})%' coverage/coverage-summary.txt || true
          node <<'EOF'
          import fs from 'fs';
          const summaryPath = 'coverage/coverage-summary.json';
          if (!fs.existsSync(summaryPath)) process.exit(0);
          const data = JSON.parse(fs.readFileSync(summaryPath,'utf8'));
          const totals = data.total;
          const thresholds = { lines: 60, statements: 60, functions: 50, branches: 40 };
          let fail = false;
          for (const [k,v] of Object.entries(thresholds)) {
            if (totals[k].pct < v) { console.error(`Coverage for ${k} ${totals[k].pct}% < ${v}%`); fail = true; }
          }
          if (fail) process.exit(1);
          EOF
      - name: Upload coverage artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage


