name: Meta Sync Labels

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  meta-sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"
      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labeler.yml
          token: ${{ steps.generate-token.outputs.token }}
